### PR TITLE
Enhanced the Alignment of Chapter Cards #12

### PR DESCRIPTION
**Pull request by Reene-Simon**
Fixed Issue #12. The chapter cards were aligned in a fashion of 4 cards per row. Other issues like uneven size of boxes, proper aligning and correct rendering on smaller screens by reducing the number of cards in each row has been completed successfully. Here's an image of the new alignment:
Issue#12

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
lovely,
Keep India Chapter first and if possible increase the width (horizontal length of the cards a little)

**Comment by Reene-Simon** [comment]
Updated the PR for Issue #12  with the required changes. Here's an image of the updated version:
Issue#12 Final
Also, the width cannot be increased further as it completely messes up with the layout of everything.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image


Just 2 more changes.
1. Remove extra spacing from the cards
2. Change united arab emirates to -> UAE

**Comment by VidhiBhatt01** [comment]
Also resolve merge conflicts

Check this out: https://www.youtube.com/watch?v=JtIX3HJKwfo

**Comment by Reene-Simon** [comment]
Made the requested changes for the Issue #12 . The video was pretty cool. Thanks for the assist. Here's an image of the updated version:
Codess Issue#12
The height of the cards cannot be reduced further as the text will go out of the box in smaller dimensions of the screen.

**Comment by Reene-Simon** [comment]
I had a couple of doubts. Is it necessary to pin the Issue no in every text? Or is it only to be done in the first message?
Also, how to set the member tag? Because I'm a part of Codess-Cafe.

**Review by VidhiBhatt01 — APPROVED** [review]
Perfect

**Comment by VidhiBhatt01** [comment]
> I had a couple of doubts. Is it necessary to pin the Issue no in every text? Or is it only to be done in the first message? Also, how to set the member tag? Because I'm a part of Codess-Cafe.

Only in the first message. 

Member tag is not needed

**Pull request merged**
