### PR TITLE
issue #4 Revise Team Member Information

### PR DESCRIPTION
**Pull request by mohitparmar1**
Screenshot (195)
solved issue #4

### CODE REVIEW

**Comment by mohitparmar1** [comment]
dont forget to add /hacktoberfest label

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Add screenshots of how the cards look on local after modifications. Issue description says  remove the whole editor in chief section. Modify details for Vidhi Bhatt in the current organizational lead card. Why does mentor 45 image have 2 photos within? If it's just for comparison, it should be added in PR description not in the commit.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
"Issue description says remove the whole editor in chief section. Modify details for Vidhi Bhatt in the current organizational lead card"
 
 Read instructions properly

**Comment by mohitparmar1** [comment]
> "Issue description says remove the whole editor in chief section. Modify details for Vidhi Bhatt in the current organizational lead card"
> 
> Read instructions properly

**Review by VidhiBhatt01 — COMMENTED** [review]
```
<div class="row">
                  <div class="col-lg-4 col-md-6 mentor-cards-home">
                    <div class="card">
                      <div class="img-bx">
                        <img src="images/mentor/43.jpg" alt="img" />
                      </div>
                      <div class="content">
                        <div class="detail">
                          <h2>
                            Riya Dev Varshney<br /><h2
                              >Organization Lead <br />SDE: Google | CSE, DTU</h2
                            >
                          </h2>
                          <ul class="sci">
                           
                            <li>
                              <a href="#"><i class="fab fa-linkedin-in"></i></a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
```

update my details here and remove editor in chief card

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
