### PR TITLE
Testimonials card modified

### PR DESCRIPTION
**Pull request by coderbysoul**
Removed blur effect on hover on testimonial cards.
This is the final website : 

https://github.com/Codess-Cafe/Codess-Website/assets/96008596/9f52c625-bda8-42f1-8ea9-ae1f25d81dba

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Thanks Arjya for doing it! 2 things are still not proper:
1. In the testimonial card, the text is not aligned properly. Left padding seems to be more.
2. For number speaks louder section, ig you added a counter effect earlier. Some other effect is there right now instead of that. The counter effect was good

**Comment by coderbysoul** [comment]
> Thanks Arjya for doing it! 2 things are still not proper:
> 
> 1. In the testimonial card, the text is not aligned properly. Left padding seems to be more.
> 2. For number speaks louder section, ig you added a counter effect earlier. Some other effect is there right now instead of that. The counter effect was good

I corrected the alignment of the testimonials card in the latest commit https://github.com/Codess-Cafe/Codess-Website/pull/109/commits/20c15c03f3f8f98b67c92cd5fa9b5aa9da1a4986 
The counter effect is still there in the numbers speak louder section, somehow it was not captured in the screen recording ,here it is: 

https://github.com/Codess-Cafe/Codess-Website/assets/96008596/d67aa085-829a-4f66-952f-ddaaa64cf3f4

**Review by VidhiBhatt01 — APPROVED** [review]
Got it, thanks a ton girl!

**Comment by coderbysoul** [comment]
> Got it, thanks a ton girl!

You're welcome di

**Pull request merged**
