### PR TITLE
Fix/copyright year

### PR DESCRIPTION
**Pull request by SulagnaKundu**
##What does this PR do?
This PR dynamically changes the copyright year in all portions of the website.

Fixes#44
##Type of change
Updated the copyright year

Screenshot of the change
image

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
This issue is not assigned to you

**Review by VidhiBhatt01 — COMMENTED** [review]
Reopen this PR if the contributor whom this is assigned does not raise a PR by tomorrow

**Comment by VidhiBhatt01** [comment]
Also resolve the merge conflicts

**Comment by SulagnaKundu** [comment]
Okay maam

**Pull request closed without merging**
