### PR TITLE
Added Scrollbar

### PR DESCRIPTION
**Pull request by Dev-Anand25**
Added scrollbar which sometime camouflage with background. gives new style...

### CODE REVIEW

**Comment by Ruchip16** [comment]
can you please provide screenshots of the before & after?

**Review by Ruchip16 — CHANGES_REQUESTED** [review]
can you please provide screenshots of the before & after?

**Comment by Dev-Anand25** [comment]
before
after

**Review by VidhiBhatt01 — COMMENTED** [review]
Did you create an issue for this?? Am sorry but we don't want this feature. Had you created an issue, we would have rejected it that time only and your effort could have been saved!

**Pull request closed without merging**
