### PR TITLE
Feat/faq expandable

### PR DESCRIPTION
**Pull request by gaurovgiri**
This PR does following: 
1. Fix indentations and  formatting in index.html.
2. Add faq-item as class name for each faqs div.
3. Add a script to find the clicked faq and click the button inside the div to expand.
4. Add a upper-caret symbol when expanded.

This PR resolves Issue No. #51.

### CODE REVIEW

**Review by aayush105 — APPROVED** [review]
LGTM!

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Add before/after photos or screen record a video for the changes you made in the PR description/comments

**Comment by gaurovgiri** [comment]
codess

@VidhiBhatt01 Do check this! The first one is the current site where you must click the text on the FAQs to expand and the second one is the changes I have created in PR in which you can click anywhere in the div to expand the FAQ-item.

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
Thanks for contributing

**Comment by VidhiBhatt01** [comment]
Man you deleted some unwanted code in fix formatting commit

**Pull request merged**
