### PR TITLE
Adding Hover to socail media link

### PR DESCRIPTION
**Pull request by Tooba-Amjad**
@VidhiBhatt01 
Hover to LinkedIn Icon is added

Screenshot (240)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
We need not change the color. Just make the icon bigger on hovering and add dark purple border

**Review by VidhiBhatt01 — APPROVED** [review]
Nvm, this is good too.

can you share a photo/video of how it looks with border?

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01  Do you still want the picture / video with the specs you share ?

**Comment by VidhiBhatt01** [comment]
yes

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01 Look
Screenshot (250)

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01
Share your views on the above hover effect ?

**Pull request merged**
