### PR TITLE
Added hover effect to the program offerings

### PR DESCRIPTION
**Pull request by Reene-Simon**
Fixed Issue #100. Added a hover effect to the icons in the program offerings section. This is what it looks like:

https://github.com/Codess-Cafe/Codess-Website/assets/112744886/8276ebc1-c27e-471c-8d16-f0b0956cdd79

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]
Can't we increase the corresponding text size too in same manner?

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 will work on it and update the PR accordingly 👍

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 made the changes requested. This is how it looks like:

https://github.com/Codess-Cafe/Codess-Website/assets/112744886/453d748b-a3e1-4d24-be06-b5dc96e788b4

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 just to let u kn. Issue #88 has been resolved by my PR (#98)  made yesterday. I was checking the responsiveness and it is looking good.

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 just to let u kn. Issue #88 has been resolved by my PR (#98) made yesterday. I was checking the responsiveness and it is looking good.

responsiveness for all screen sizes?

**Review by VidhiBhatt01 — APPROVED** [review]
Merging it but if possible try to make it smoother

**Pull request merged**
